/**
 * Exports a DB import session as a test fixture JSON (optionally anonymized).
 *
 * Usage:
 *   DB_PATH=/path/to/dev.db npx tsx server/scripts/export-fixture.ts \
 *     --import-id <ID> --anonymize --project-key PROJ \
 *     --out server/tests/fixtures/tn-fixture.json
 *
 * Anonymization replaces external_id, title, and external_link.
 * All transitions, timestamps, ticket_type, and created_at are preserved.
 */

import Database from 'better-sqlite3'
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))

const args = process.argv.slice(2)
function getArg(name: string): string | null {
  const i = args.indexOf(`--${name}`)
  return i >= 0 ? (args[i + 1] ?? null) : null
}

const importId = getArg('import-id')
const out = getArg('out')
const anonymize = args.includes('--anonymize')
const projectKey = getArg('project-key') ?? 'PROJ'

if (!importId || !out) {
  console.error('Usage: --import-id <ID> --out <path> [--anonymize] [--project-key KEY]')
  process.exit(1)
}

const dbPath = process.env.DB_PATH ?? resolve(__dirname, '../dev.db')
const db = new Database(dbPath, { readonly: true })

const imp = db.prepare('SELECT * FROM import_sessions WHERE id = ?').get(importId) as any
if (!imp) {
  console.error(`Import not found: ${importId}`)
  process.exit(1)
}

const config = db.prepare('SELECT * FROM project_configs WHERE id = ?').get(imp.config_id) as any
const tickets = db.prepare(
  'SELECT * FROM tickets WHERE import_id = ? ORDER BY rowid'
).all(importId) as any[]
const allTransitions = db.prepare(`
  SELECT tt.* FROM ticket_transitions tt
  JOIN tickets t ON tt.ticket_id = t.id
  WHERE t.import_id = ?
  ORDER BY tt.transitioned_at, tt.rowid
`).all(importId) as any[]

const byTicket = new Map<string, any[]>()
for (const t of allTransitions) {
  if (!byTicket.has(t.ticket_id)) byTicket.set(t.ticket_id, [])
  byTicket.get(t.ticket_id)!.push(t)
}

const fixture = {
  _comment: `Anonymized export of "${config.name}" import. Generated by export-fixture.ts.`,
  _config: {
    cycle_time_start_status: config.cycle_time_start_status,
    cycle_time_end_status: config.cycle_time_end_status,
    cycle_time_mode: config.cycle_time_mode,
    lead_time_start_status: config.lead_time_start_status ?? null,
    lead_time_end_status: config.lead_time_end_status ?? null,
    status_order: JSON.parse(config.status_order),
  },
  source_type: imp.source_type,
  project_key: anonymize ? projectKey : imp.project_key,
  exported_at: imp.imported_at,
  tickets: tickets.map((ticket, i) => {
    const num = String(i + 1).padStart(3, '0')
    const transitions = (byTicket.get(ticket.id) ?? []).map((t: any) => ({
      from_status: t.from_status ?? null,
      to_status: t.to_status,
      transitioned_at: t.transitioned_at,
    }))
    return {
      external_id: anonymize ? `${projectKey}-${num}` : ticket.external_id,
      title: anonymize ? `Ticket ${num}` : ticket.title,
      ticket_type: ticket.ticket_type,
      created_at: ticket.created_at,
      external_link: anonymize ? null : (ticket.external_link ?? null),
      transitions,
    }
  }),
}

const outPath = resolve(out.startsWith('/') ? out : resolve(process.cwd(), out))
writeFileSync(outPath, JSON.stringify(fixture, null, 2))
console.log(`Exported ${tickets.length} tickets → ${outPath}`)
console.log(`Config: ${config.name}`)
console.log(`  mode: ${config.cycle_time_mode}`)
console.log(`  cycle: ${config.cycle_time_start_status} → ${config.cycle_time_end_status}`)
console.log(`  lead:  ${config.lead_time_start_status ?? 'created_at'} → ${config.lead_time_end_status ?? config.cycle_time_end_status}`)
